# Generated by Django 4.1.4 on 2023-06-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_aboutme_profile_image_alter_aboutme_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='skills',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skills',
            field=models.ManyToManyField(to='info.skill'),
        ),
    ]
