# Generated by Django 4.1.4 on 2023-06-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0003_remove_aboutme_skills_aboutme_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='company_logos/')),
                ('post_name', models.CharField(max_length=150)),
                ('what_i_did', models.TextField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('skills_used', models.ManyToManyField(to='info.skill')),
            ],
        ),
    ]
